### ISSUE TITLE
Create CodeLab OC Web Site (Github Pages)

### ISSUE THREAD

**Issue by thebearingedge** [codelaboc/hellocodelab#13]
https://pages.github.com/

**Comment by thebearingedge** [comment]
- [ ] Code of Conduct
- [ ] Meetup Locations

**Comment by jonofcho** [comment]
Rails pl0x :D

**Comment by dotproto** [comment]
I stubbed out the repo: https://github.com/codelaboc/codelaboc.github.io

**Comment by leighphan** [comment]
Hey CodeLabbers! Outline of CodeLab site is up and open to suggestions and additional content.

Check it out at: https://github.com/codelaboc/codelaboc.github.io/pull/1/files

**Comment by leighphan** [comment]
Thanks to @interdigitize for pairing on this. https://codelaboc.github.io/ is up!

**Comment by jonofcho** [comment]
woahhhh
