### ISSUE TITLE
Create a Logo for the Group!

### ISSUE THREAD

**Issue by thebearingedge** [codelaboc/hellocodelab#15]
Maybe a flask, beaker, or test tube bubbling with `1`'s and `0`'s

**Comment by IanDCarroll** [comment]
We need someone to assign themselves this task. Anyone got some graphic design or brave enough to try?

**Comment by leighphan** [comment]
Forgot to assign - I'm jamming on this. @blikethat also expressed interested. And @svincent?!

**Comment by interdigitize** [comment]
I took @thebearingedge 's idea and mocked up a logo. Here is the link, <img width="242" alt="code lab logo mockup" src="https://cloud.githubusercontent.com/assets/17533722/18258635/06fabd52-738e-11e6-9d1d-3abb38c28ac8.png">

**Comment by interdigitize** [comment]
...oh it embedded it. Cool! Send me thoughts/edits.

**Comment by interdigitize** [comment]
@leighphan @IanDCarroll

**Comment by thebearingedge** [comment]
AWESOME 🎉

**Comment by leighphan** [comment]
@blikethat Rad! That's what I had in mind too. Let's put "Code" and "Lab" together (stylized that way). I imagined we could have a version that's orange. What do y'all think?
