### ISSUE TITLE
[CodeLab 003] Mon., Aug 29, 2016

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#23]
## August 29, 2016: CodeLab 003

**Location:** Pro Desk Space

**Attendees:**
Leigh
Daniel 
Stoil
Joseph
Simeon
Holly
Ashley
Bill
Jorg
Daniel
Kevin
Kami

**Thanks to our sponsors** Yeti Media & Pro Desk Space for food & drinks!
## Show & Tell
- **Joseph (@chengyus)**: Currently volunteering on project with Chinese Catholic Church (#21)
- **Leigh (@leighphan)**: Working on the CodeLab website (Follow & contribute on https://github.com/codelaboc/codelaboc.github.io)
- **Stoil (@stoich)**: building a game on Unity: Space Game, https://github.com/Doychev/spacegame
- **Simeon (@svincent)**: snap.today! (#16)
- **Kami (@blikethat)**: Working on a project called Fortune Kooky, in which you enter a phone number and it sends a random fortune to you.
### **Show & Tell**
- Share with us how your project's developed
### **Pair Programming!**
- Install exercism.io (Most of us are doing the JavaScript track: **http://exercism.io/languages/javascript**)
- Get as far as you can on the exercises, then come with questions
- We're going to pair program on the exercises together!
  **\- Questions? Let's find the answers together on Slack!**

_Feel free to add anything missed_

**Comment by bluAsterisk** [comment]
I know C, C++, Java, and I'm learning Assembly Language with x86 processors!

**Comment by ghost** [comment]
Working on learning javascript and python 😄

**Comment by kangashley** [comment]
JavaScript (+ libraries like Leaflet & p5), Java, Ruby (+ Rails), data structures & algorithms

**Comment by DerCSpringer** [comment]
Daniel: learning swift, and I know objective-c, java, c++
Project: "Life Planning" on Apple app store

**Comment by dotproto** [comment]
Simeon here! I'm working on learning JavaScript, specifically ES2015/ES2016 features. Also want to explore new web tech.

Today I'm panning to work on [snap.today](https://snap.today)! Issue #16 describes the project in detail.

**Comment by interdigitize** [comment]
Kamie: I am learning JavaScript & Processing. 
The project I am working on is called Fortune Kooky.

**Comment by davidws22** [comment]
knowledge of c++, c, java.
Wanting to learn python

**Comment by chengyus** [comment]
Joseph: Language: Ruby (on Rails), Coffeescript, Interested in learning latest Javascript (7th Edition - ECMAScript 2016), working on private Project: CCC-info (#21), but also interested on working on working open data & map based projects from the 2nd week project sharing.

**Comment by stoilsky** [comment]
Stoil visiting from Europe, I work with C# and JavaScript: I'm working on 2D Unity game with pvp multiplayer playable over the interwebs:
https://github.com/Doychev/spacegame
 Language is C#

**Comment by wdalessi** [comment]
Javascript and Java. Javascript to help with WordPress, etc.

**Comment by jorggaubmann** [comment]
Jorg: Fullerton. Work with .NET or as some say .NOT! would like to expand my knowledge in application development.
