### ISSUE TITLE
[CodeLab 004] Mon., Sep 12, 2016

### ISSUE THREAD

**Issue by kangashley** [codelaboc/hellocodelab#24]
## September 12, 2016: CodeLab 004 in Session 🔬

Location: Pro Desk Space

Attendees:
@kangashley
@leighphan 
@jorggaubmann 
@ntreadway 
@theresaluu 
@davidws22
@bluAsterisk 
@svincent 
@jonofcho 
Greg (Welcome!)

Sponsors: Thanks to Yeti Media & Pro Desk Space for covering 🍕  & 🍺!
## Stand Up

No stand-up comedy (yet) but we came together in a circle to talk about our goals and headaches.
- **Simeon (@svincent)** is learning web components (which might become a talk for an upcoming session?!).
- **Jon (@jonofcho)** is working on a website that connects past and present members of KASA (Korean American Students Association) and is trying to squash all the bugs so he can move on with his life.
- **Greg** hopes to build his own game console.
- **Jorg (@jorggaubmann)** would like to catch up to current web dev tools like JavaScript, maybe through a project like a simple form for Pro Deskers to sign in.
- **Leigh (@leighphan)** is looking for tools to temporally map her family's history and movement.
- **Ashley (@kangashley)** is now a co-organizer (!) and is starting to learn the paradigm of functional programming as well as data structures and algorithms via a back-end language (Java).

_@ntreadway, @theresaluu, @davidws22, @bluAsterisk & others, feel free to ✏️  anything that you shared but wasn't mentioned above._
## In the Lab
- Theresa and Jon were squashing Ruby bugs in Jon's site (go get 'em).
- David (Mac), Kevin (Linux), and Jorg (PC) installed the [JavaScript track](http://exercism.io/languages/javascript) of [Exercism](http://exercism.io/) and got through the first exercise, `hello-world`! 
- The setup documentation was not as linear as expected, so Ashley compiled a Getting Started guide (for Mac and PC, although David managed with Linux) and will clean that up to share here soon. Shoutout to Leigh, Nick, Simeon, and Greg from taking time from their projects to help with installing as well as programming a la TDD (test-driven development) with [Jasmine](https://github.com/jasmine/jasmine).
- For those new to JavaScript, Ashley added some resources [here](https://github.com/codelaboc/hellocodelab/issues/12).
### Stand Up/Show & Tell
- Share with us any progress and roadblocks, tears and all.
### Pair Programming
- How long can you exercise with a buddy?

_Look out for us on [Meetup](http://www.meetup.com/Orange-Countys-Creative-CoWorking-Downtown-Fullerton/) to RSVP and invite others. See you next time! 👋_

**Comment by kangashley** [comment]
Regardless of what language you exercise with, get started with Exercism [here](https://paper.dropbox.com/doc/Working-exercism.io-qXCQTNsfNMRfJJnzvAP9v)! If anything's unclear (as I only addressed issues that came up for me and others I worked with), please leave a comment in the doc or below.

(@leighphan, should this become a separate issue?)

**Comment by leighphan** [comment]
@kangashley very detailed notes on getting started on exercism! This would be a good addition to #12, but let's make it a separate issue to in the future add to our website.

**Comment by machikoyasuda** [comment]
@kangashley @learningnerd has written pretty good instructions/story about how to install Exercism for JavaScript on Windows here http://learningnerd.com/2015/05/06/exercism/

http://learningnerd.com/2015/05/12/more-javascript-exercism/

**Comment by machikoyasuda** [comment]
More Exercism learnings/documentation etc

https://github.com/fullstackla/pairing-meetup/blob/master/how-to-auto-run-tests-js.md

https://github.com/fullstackla/pairing-meetup/issues/7

**Comment by machikoyasuda** [comment]
I think these https://github.com/fullstackla/pairing-meetup/issues/7 are super great and we should consider pushing these up to exercism.io the website!! https://paper.dropbox.com/doc/Working-exercism.io-qXCQTNsfNMRfJJnzvAP9v http://exercism.io/languages/javascript/installing

We can make a PR at Hacktoberfest to include better screenshots/commands etc to this pg http://exercism.io/languages/javascript/installing
