### ISSUE TITLE
[CodeLab 005] Mon., Sep 26, 2016

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#25]
## 🎉 September 26, 2016: CodeLab 005 in Session ☀️🔬⚗

Location: Pro Desk Space

**Attendees**:
@svincent (Simeon)
@lapaperboy (Kristopher)
@leighphan (Leigh)
@gr2m (Gregor)
@hollyhaho (Holly)
@7hru57 (Michael Lee)
@jonofcho (Jon Cho)
@Nisageee (Nisa)
## Stand Up

We did a roundtable to share introductions, interests, challenges, along with personal fun facts.

Simeon (@svincent): Here to help beginners! On the side, working on researching web components.
Kristopher (@lapaperboy): Writer-Journo who writes transportation. Currently working on a book!
Leigh (@leighphan): Learning JS to apply to interactive mapping.
Gregor (@gr2m): Visiting from LA (FullstackLA). A founder of [hood.ie](https://github.com/hoodiehq), an open source platform providing a backend for web applications. Welcome! 🌟
Holly (@hollyhaho): CSUF CS student, breaking out of the curriculum and learning JS on exercism!
Michael (@7hru57): Software dev; trying out new meetups in OC. Learning Python on exercism! Welcome 🌟
Jon (@jonofcho): Rails developer, CSULB alum. Building online alumni network for KASA student group (Korean American Student Assoc.).
Nisa (@Nisageee): First time at CodeLab. Working on learning Swift! 🌟
## In the Lab

Simeon coached Leigh & Kristopher as they worked on Javascript track on exercism.
Initially we tried installing exercism on Chromebook, which requires:
- Access command line via CTRL + alt + T
- To run Linux on Chromebook, install Crouton, or Cloud9
- Ultimately we used a laptop with exercism installed. **To-Do**: gather notes on how to install exercism on Chromebook to add to Getting Started Guide!

Holly, Gregor, worked on Javascript exercism track. Michael worked on Python on exercism. 😈 🐍
Nisa worked on personal projects while updating Xcode.
## 📢 Announcements! 📅

**[ Oct. 15, 2016 ] [Girl Develop It Study Group](https://www.meetup.com/Orange-Countys-Creative-CoWorking-Downtown-Fullerton/events/234424631/) - Fullerton Edition**
Girl Develop It is a community offering workshops and courses in web development for women-identifying learners. GDI is women-inclusive, not women-exclusive - come join us for the first Fullerton GDI LA Study Group! 

**[ Oct. 16, 2016 ] CodeLab x FullstackLA Hacktoberfest / boba.js**
[Hacktoberfest](https://hacktoberfest.digitalocean.com/) is a hackathon event started by GitHub + Digital Ocean to encourage and introduce involvement in open source projects. This event is in collaboration with our pals at FullstackLA and will take place at Pro Desk Space.

Submit 4+ pull requests and get a limited edition Hacktoberfest 2016 t-shirt!
We'll be venturing around Downtown Fullerton for local snacks and boba. :)

**[ Oct. 21, 2016 ] Software Craftsmanship North America @ USC**
http://scna.softwarecraftsmanship.org/
- Grants to cover registration are available for individuals from underrepresented groups

**[ Oct. 21-22, 2016 ] Rails Girls LA**
http://railsgirls.com/la
Come learn or mentor a weekend workshop for Ruby on Rails. Apply by **Oct. 8!**

**[ Oct. 22-23, 2016 ] Girl Develop It Website Weekend**
https://girldevelopit.ticketleap.com/website-weekend-la/details
Join teams in this GDI hackathon to build websites for non-profits!
### Stand Up/Show & Tell

Share with us any progress and roadblocks, tears and all.
### Pair Programming

Share which exercism challenges you tested, passed, what issues you had!
Stay in touch on our [CodeLab exercism group](http://exercism.io/teams/codelab-oc/streams).
If you need any help, find us on Slack :)

Look out for us on Meetup to RSVP and invite others. See you next time! 👋

**Comment by ghost** [comment]
I like these recaps!
