### ISSUE TITLE
[Hacktoberfest!]

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#28]
# Welcome to Hacktoberfest!

We'll be pair programming on open source projects today, primarily @hoodiehq!

Follow our outline for today: [https://github.com/leighphan/pairing-meetup/blob/master/hacktober_2016.md](https://github.com/leighphan/pairing-meetup/blob/master/hacktober_2016.md)

Add our tag to the issues you work on! :) : "Made at CodeLabOC 🍊 🎃" 
### Here are all @hoodiehq issues:

https://github.com/issues?utf8=%E2%9C%93&q=fullstackhacktoberfest+
### Post your name, and languages!

Julio: @julioberina - Ruby/Rails
Hong: @xuhdev - language agnostic
Kamie: @interdigitize - JavaScript, HTML/CSS
Jeffrey: @dinhjeffrey - JavaScript, Swift
Gregor: @gr2m - JavaScript
Simon: @simonyangme - Haskell, Swift, JavaScript
Leigh: @leighphan - JavaScript, HTML/CSS
Machiko: @machikoyasuda - Ruby, JavaScript
Ashley: @kangashley - JavaScript, HTML/CSS
Kit: @kpearson - Ruby, JavaScript
Theresa: @theresaluu - Ruby, JavaScript, jQuery, HTML/CSS
Jimmy: @jtru71 - language agnostic
Jim: @jimthoburn - JavaScript, HTML/CSS
Nhat: @nhatbui - Python, C++, JavaScript
Mustafa: @mustafaUW - C, Java
Greg: JavaScript, PHP, Java, Verlog
Simeon: @svincent - JavaScript, HTML, CSS
Hector: @ghalander
Julian: @avongenesis

**Comment by machikoyasuda** [comment]
One PR made paired with @interdigitize & @dinhjeffrey https://github.com/hoodiehq/hoodie-client-task/pull/32

**Comment by machikoyasuda** [comment]
Search for more: https://github.com/search?q=made+at+codelaboc&type=Issues&utf8=%E2%9C%93

**Comment by machikoyasuda** [comment]
One PR made paired with @dinhjeffrey https://github.com/hoodiehq/hoodie-account-server/pull/193

**Comment by machikoyasuda** [comment]
Another PR from @simonyangme https://github.com/hoodiehq/hoodie-account-server/pull/192

**Comment by machikoyasuda** [comment]
Another PR from @simonyangme https://github.com/hoodiehq/hoodie-account-server-api/pull/10

**Comment by machikoyasuda** [comment]
Another pr! @dinhjeffrey https://github.com/hoodiehq/hoodie-account-server/pull/194

**Comment by machikoyasuda** [comment]
https://github.com/hoodiehq/hoodie-camp-tutorial/pull/32

**Comment by kangashley** [comment]
hoodiehq/camp#79 Made my first PR to @hoodiehq, which was merged!

_s/o to @svincent for helping with command line roadblocks, @leighphan and @gr2m for reviewing_
