### ISSUE TITLE
[CodeLab 007] Mon., Oct 24, 2016

### ISSUE THREAD

**Issue by kangashley** [codelaboc/hellocodelab#29]
# 🎉  October 24, 2016: CodeLab 007 in Session :alembic:

**Location:** Pro Desk Space (Thank you, @jorggaubmann!)

**Attendees:**
@kangashley
@leighphan 
@jimthoburn
@gr2m
@romantickowloon 🌟
@justinjyoo 🌟
@josephmvu 🌟
@dinhjeffrey
@hellotata 🌟
@Jamiejekim 🌟
@svincent 
(🌟 = Welcome, First Timers at CodeLab!)

Join our [Slack](http://codelaboc.herokuapp.com/)!
## Stand Up 🙌
- Diving into a new or increasingly unfamiliar language via [Exercism](http://exercism.io/)–JavaScript is the popular one! Java was mentioned as well as Ruby, as Rowan attended last weekend's [Rails Girls](http://railsgirls.com/).
- Recaps of the 2nd annual [SCNA](http://scna.softwarecraftsmanship.org/) (hosted by [8th Light](https://8thlight.com/), where our LA friends @fullstackla meet!) and [Website Weekend](http://websiteweekend.la/) (hosted by [Girl Develop It LA](http://www.meetup.com/Girl-Develop-It-Los-Angeles/))
## In the Lab 🔬
- Setting up Exercism: [Ashley's documentation](https://paper.dropbox.com/doc/Working-exercism.io-qXCQTNsfNMRfJJnzvAP9v)
- While walking Jamie through Exercism, Simeon asked if there was a good resource for learning JavaScript and Node.js basics: [Eloquent JavaScript](http://eloquentjavascript.net/), [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS), [NodeTogether](http://www.nodetogether.org/), [Sergey Titov's list](https://github.com/sergtitov/NodeJS-Learning)
- Tell us about your small wins and roadblocks below! 
## Announcements 📢
- Last Sunday, we hosted our first local Hacktoberfest 🍊🎃 , also our first collaboration with Fullstack LA. Hacktoberfest began as a partnership between GitHub and Digital Ocean to encourage participation in open source, and you can sign up [here](https://hacktoberfest.digitalocean.com/). Submit four pull requests to win a free T-shirt! 

> Free and Open Source Software (FOSS) projects are built under open source licenses and built by an open community – meaning anyone can contribute to changing, building, and improving the software. Some examples include Linux, GitHub, jQuery, Homebrew, and Hoodie (managed by @gr2m!), to name a few. Many FOSS projects are managed on GitHub. Read [Gregor's thoughts on open source](http://hood.ie/blog/welcoming-communities).
- See: [Fullstack LA's awesome list](https://github.com/fullstackla/awesome-help-wanted), [First Timers Only](http://www.firsttimersonly.com/), [Your First PR](http://yourfirstpr.github.io/), [Up For Grabs](http://up-for-grabs.net/#/), search GitHub for issues with labels like `hacktoberfest`, `first-timers-only`, `help wanted`, or some variation of `newbiefriendly`
## Plans for Next Meeting (11/07) 🔮
- [24 Pull Requests](http://24pullrequests.com/) for December 🎄⛄️
- Reviving [Code for OC](https://twitter.com/CodeforOC) 🍊 in the [Code for America](https://www.codeforamerica.org/)/@codeforamerica network
- Onboarding a long-term project together
- Pair programming, of course

_Look out for us on [Meetup](https://www.meetup.com/Orange-Countys-Creative-CoWorking-Downtown-Fullerton/) to RSVP and invite others. See you next time! 👋_

**Comment by leighphan** [comment]
@jimthoburn & I are pairing on exercism.io JS track!

Update: Nice work, everyone! @jimthoburn and I reached the 5th exercise, 'Bob' on the JavaScript exercism track. Trickiness level upped a notch! :)

**Comment by dinhjeffrey** [comment]
@hellotata and I are pairing up on exercism.io!

**Comment by justinjyoo** [comment]
@josephmvu are pairing together for exercism.io

**Comment by gr2m** [comment]
@romantickowloon and I are pairing together on exercism.io Python Track

**Comment by Jamiejekim** [comment]
Reviewing the basics
