### ISSUE TITLE
[CodeLab 008] Mon., Nov 07, 2016

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#32]
# 🎉  November 7, 2016: CodeLab 008 in Session :alembic:

**Location:** Pro Desk Space (Thank you, @jorggaubmann!)

**Attendees:**
Theresa: @theresaluu 
Jimmy: @jtru71
Hector: @ghalander
Leigh: @leighphan
Kris: @lapaperboy
Joseph: @josephmvu

## Stand Up 🙌
Intros + discussed projects, languages we're working on in the Lab and in general.
@theresaluu: usually develops in Rails, now learning Angular 2.
@jtru71: starting out on JavaScript. Just finished up a long week running BlizzCon '16 at Anaheim Convention Center! 👾 
@ghalander: Participated in [CitrusHack](https://citrushack.com/#/schedule) at UCR in Oct - learned how to make an in-browser game using JS!
@leighphan: Currently working on graduate school apps and portfolio! Also prototyping a food history game/project.
@lapaperboy: Continuing on Exercism track; brought some cool books to share!
@josephmvu: Building website at work and concurrently learning JS.

## In the Lab 🔬
Hector worked on personal projects, while we worked on Exercism JS track. Jimmy and Theresa installed and paired on Exercism JS track, completing the Leap Year exercise.

Leigh, Joseph, Kris mob programmed on Exercism JS track. We worked up to exercise "Bob". Found that tonight's example (completed on Joseph's) was much cleaner compared to our previous attempts on this exercise. 👌 

Thanks to @lapaperboy for bringing graphic novels for our CodeLab Floating Library :) We looked at The Last Man, and John Sacco's The Great War.

### [SoCal Code Camp](http://www.socalcodecamp.com/) @ USC - Nov. 12-13th, 2016
- Talks, workshops by locals in the industry. [Several tracks](http://www.socalcodecamp.com/tracks.aspx), including Career Development, Web Dev, New Developer, Intro to Git/GitHub, and developing in VR and more!
- FREE!

## Plans for Next Meeting (11/21) / Future! 🔮
- [24 Pull Requests](http://24pullrequests.com/) for December 🎄⛄️
- Reviving [Code for OC](https://twitter.com/CodeforOC) 🍊 in the [Code for America]/@codeforamerica network

**Winter / Holiday Party!**
We'll have a low-key winter-themed CodeLab in Dec, (Dec 5 or 19th)!  

**💡Group Quarterly Projects💡**
- In 2017: we'd like to create short-term group projects (constrained by deadline) that would last about 3 months max. This would be a great way for all-levels to commit to a short project, build skills, and add to our portfolios.
- Civic projects (a la Code for America) would be a great starting point. **Start brainstorming if you'd like to pitch a project idea in December**!!

**CodeLab Floating Library 📚:** Calling the CodeLab community! We invite you to bring some books to share at future meetups. Technical-related not required. :)

Look out for us on [Meetup](https://www.meetup.com/Orange-Countys-Creative-CoWorking-Downtown-Fullerton/) to RSVP and invite others. See you next time! 👋

**Comment by machikoyasuda** [comment]
i heart you all <3 

PS: https://www.digitalocean.com/company/blog/open-source-at-its-hacktoberbest/
