### ISSUE TITLE
[CodeLab 011] Mon, Dec 19, 2016

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#35]
## Stand Up 🙌
Who's here:
Leigh @leighphan
Gregor @gr2m
Simeon @svincent 
Kamie (@interdigitize)
Sharif (@shekobmbm) 🌟 
Rob (@honzo0481) 🌟
Spencer (@Muhahahahaz)
Nolan (@nolanchan) 🌟
(🌟 = first-timer)

## Stand Up 🙌 
Leigh is currently building web map side projects - all about Leaflet! 
Welcome back, Gregor! Code Team Lead at @hoodiehq. Seasoned JS dev. Here to help :)
Simeon is working on a side project: offline blog platform. Here to help :)
Kamie was accepted to HackReactor! Whoo! 🎉 
Sharif is learning web development and aims to combine prior knowledge of SQL DBs. Suggestions and tips? Let Sharif know!
Rob currently uses Python at work and is looking to further sharpen skills in Python and web dev.
Spencer is looking to apply his CS background into backend programming - suggestions and guidance welcome!
Nolan is a Ruby developer, aiming to practice more JS. Interested in civic tech projects.

### 2017 Civic Data Projects
**Urban Drool Tool**
- Getting a kick-start on civic projects for 2017: OC Public Works, Moulton Niguel Water District, and the [CA Data Collaborative](https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge) are collaborating to collect and visualize water usage data for the Moulton Niguel Water District.
- Interested in collaborating w/ CodeLab to create a front-end website to visualize the data, increase public awareness, and encourage and incentivize residents to reduce unnecessary water usage.
- Questions/interested? Contact @leighphan. Stay tuned for more info in Jan!

**We have a few outstanding projects as the year winds down:**
**_Anyone want to pair on these?_** :raised_hand_with_fingers_splayed: 
- [ ] Add #12 [Learn to Code Resources] and #30 [Calendar/Events Page] to http://codelaboc.github.io
- [ ] #27 [Submit Pull Request to improve Exercism setup documentation]

## In the Lab 🔬
**JavaScript 30**
- We started up [Javascript 30](https://github.com/wesbos/JavaScript30) on the projector.
- Rob, Kamie, Sharif, Leigh started the first challenge of JS30 (interactive in-browser drumkit!) with the help of Simeon.
- 👉 Collaborate & talk JS30 on our #javascript30 slack channel 👈 
- Spencer set up his new machine running 💻 .
- Nolan and Gregor worked on side projects. Simeon also focused on side projects, at times even mentoring w/o having to looking at our screen. ✨ 

## Plans for Next Meeting (01/09/2017) + Future 🔮
- :snowman_with_snow: 🌠  Enjoy the holidays! ❄️ 🎊 
- Down time? Suggested Reading:
- [24 ways](https://24ways.org/) and [Web Advent Calendar](http://web.advent.today/) - advent calendars of publications on wed design and development goodness ⛄️
- Nicole Fenton (@nicoleslaw)'s writing for the web with style & purpose: http://nicolefenton.com/writing/ 🍵
- Keep in touch & send any questions / resources on Slack!
- See you in 2017!

**Comment by interdigitize** [comment]
Regarding plans for the future, what do you think of having an event in a couple months to showcase projects?

**Comment by leighphan** [comment]
@interdigitize That's the idea with CodeLab Camp! Also feel free to share in-progress show-n-tell at each CodeLab!

**Comment by kangashley** [comment]
So instead of 24 PRs, I've been doing _n_ days of reading [24 ways](https://24ways.org/) and [Web Advent Calendar](http://web.advent.today/)! ⛄️
*and @nicoleslaw's [writings](http://nicolefenton.com/writing/) 🍵
