### ISSUE TITLE
[CodeLab 012]: Mon, Jan, 2017

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#36]
## Stand Up 🙌
Who's here:
Leigh
Ashley
Gregory (@realspoon) 🌟
Michael (@michaeljgilmore) 🌟
Grant Sharp (OC Public Works)
Nhat Bui 
Joe
Josie
Nolan
Michelle Huang (@itsmhuang) 🌟
Rob
Bijan (@bfazeli) 🌟
Michelle Rodriguez
Mohamed (@Ameno-) 🌟
(🌟 = first-timer)

## Stand Up 🙌 
Gregory is new to Fullerton! A seasoned Java developer, now interested in Python and Open Source.
Michael web developer at MEDL Mobile. Here to help!
Grant Sharp is a natural resources manager at OC Public Works - here to speak on the Urban Drool Tool project.
Nhat is a JS developer. Here to learn and collaborate.
Joe has been teaching himself JS for about a year.
Josie is getting started on command line, then HTML/CSS.
Nolan is a Ruby developer, interested in projects for non-profits and collaborating.
Michelle Huang (@itsmhuang) is a front-end developer. 🌟
Rob creates Python tools; working on machine learning.
Bijan (@bfazeli) is a CS student, working towards a MS in CS. 🌟
Michelle Rodriguez is a front-end developer; uses Wordpress and is learning JS.
Mohamed (@Ameno-) is a JS developer and instructor at Skillshare.🌟

### 2017 Civic Data Projects
**Urban Drool Tool**
- Getting a kick-start on civic projects for 2017: OC Public Works, Moulton Niguel Water District, and the [CA Data Collaborative](https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge) are collaborating to collect and visualize water usage data for the Moulton Niguel Water District.
- Interested in collaborating w/ CodeLab to create a front-end website to visualize the data, increase public awareness, and encourage and incentivize residents to reduce unnecessary water usage.
- Questions/interested? Contact @leighphan. Stay tuned for more info in Jan!

## In the Lab 🔬
Presentation: **Grant Sharp**, OC Public Works
- OC Public Works Open Data Repo: oc.ocpw.arcgis.com
- Org also provides environmental resource mgmt, watershed planning for areas impacted by stormwater runoff
- OCPW is good at collecting the data, but less experienced at manipulating the data
- Data initiative stems from 2016 CA Water Data Challenge: http://waterchallenge.data.ca.gov/
- Michael (used to work with Forge 54) & Bijan talked shop on web dev

Demo: **PhantomJS**
- Joe led demo on [Phantom JS](https://github.com/ariya/phantomjs/)
- Joe, Mohamed, Leigh, Michelle H., Michelle R., Ashley

Pair Programming: **Exercism**
- Michael paired with Bijan and Nolan
- Gregory & Rob paired on Python Exercism

## Plans for Next Meeting (01/23/2017) + Future 🔮
- Stay tuned for more info on the Urban Drool Tool project!

**Comment by medlmichael** [comment]
Michael @michaeljgilmore
Thrilled.
