### ISSUE TITLE
[CodeLab 016]: Mon, Mar 13, 2017

### ISSUE THREAD

**Issue by kangashley** [codelaboc/hellocodelab#40]
# 🎉 March 13, 2017: CodeLab 016 in Session :alembic:

Who's here:
Ashley (@kangashley)
Carlos (@ccarmona1981)
Andres (@andres-mygithub)
Jim (@jimthoburn)
Rob (@honzo0481)
Gregory (@realspoon)
Daniel (@ham-d) 🌟
Nolan (@NolanChan)
(🌟 = first-timer)

## Stand Up 🙌 
- Ashley is reading _The User Experience Team of One_ by Leah Buley.
- Daniel is a freelance web developer building his portfolio with projects like using the Spotify API to add new features (Rob suggests adding an "Unlike" function in the Radio feature). He found us through Meetup. Welcome!
- Andres is exploring Google Finance.
- Carlos is hacking QR codes of local paths using a hosted network as well as a turntable with Arduino, projects he would like to open source. He asks about the Urban Drool Tool project methodology (issues in the Kanban board), testing iterations (none at the moment), and how to run locally (Docker).

## Announcements 📢
- Welcome! Review of our [Code of Conduct](http://maptime.io/code-of-conduct/).
- If you haven't already, complete our [intro survey](https://docs.google.com/forms/d/e/1FAIpQLSdl-GAKJor_YcPfZWbCpim3RW9n-FOdSsUJXdh8PnLDSc2vdQ/viewform?c=0&w=1) and [workshop idea survey](https://codelab1.typeform.com/to/RoFKb2) and join our [Slack](https://codelaboc.herokuapp.com/)!
- Check out an open source project Jim worked on ([Food Oasis LA](https://github.com/foodoasisla/)), part of @hackforla, which is seeking contributions on a handful of projects.
- [Mar 17] CodeNewbie's Codeland Conference [scholarship application](https://docs.google.com/forms/d/e/1FAIpQLSfEP6QKkQ9p4zXpR96Ntrr8M9SSBZ4xaej3RKxpGHj2LV_F0g/viewform) due
- [Apr 22] [Arts Access Datathon](http://artsdatathon.org/)

## In the Lab 🔬
- Urban Drool Tool [project board](https://github.com/codelaboc/CA-Stormwater-Data-Challenge/projects/1), #group-projects internal group discussion channel in Slack, #urbandrooltool project collaborators channel in Slack
   - Running on Docker
   - Jim helps Daniel set up Jekyll
- Personal projects

# Plans for Next Meeting (03/27/2017) + Future 🔮
- Latest discussion with OC Public Works, which involves using a per-capita water use number: https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge/issues/2#issuecomment-286269445
- Getting lat/lng data of the discharge points for a feature in our style object, which likely involves reprojecting shape files (.shp) to Mapbox's coordinate system (using QGIS?)

**Comment by jimthoburn** [comment]
Thank you for hosting CodeLab yesterday, Ashley! This is a great writeup.  : )
