### ISSUE TITLE
[CodeLab 025]: Mon, Aug 21, 2017

### ISSUE THREAD

**Issue by honzo0481** [codelaboc/hellocodelab#48]
# 🎉 Aug 21, 2017: CodeLab 025 in Session :alembic:

Who's here:
Simeon (@svincent)
Rob (@honzo0481)
Jim (@jimthoburn)
Danny (@dannylew12)
Kero (@CMYKero)
Kyle (@fujisawakyle) 
Philip (@philiplaucpa) 🌟
Roni 🌟
(🌟 = first-timer)

## Stand Up 🙌

- Kyle just started an internship at a nonprofit. Good luck, Kyle!
- Roni is a CS student interested in AI.

## Announcements 📢
1. CodeLab meets WEEKLY! 🎉 
- Review of our [Code of Conduct](http://maptime.io/code-of-conduct/). If you haven't already, complete our [intro survey](https://docs.google.com/forms/d/e/1FAIpQLSdl-GAKJor_YcPfZWbCpim3RW9n-FOdSsUJXdh8PnLDSc2vdQ/viewform?c=0&w=1) and [workshop idea survey](https://codelab1.typeform.com/to/RoFKb2). Follow us on [Twitter](https://twitter.com/codelaboc) and [Slack](https://codelaboc.herokuapp.com/)!
- First week of month: Onboarding for newcomers, new projects, project/language you started in the previous month
- Once a month: Urban Drool Tool work session
- Rest of the month: Workshops
- Pair programming track: @svincent has been moving the [JavaScript Exercism exercises to Glitch](https://glitch.com/edit/#!/codelab-exercism?path=README.md:1:0)—so you don't have to worry about setting up! We are interested in figuring out how to move exercises for other languages to Glitch.
2. Upcoming events
- **[10 am–4 pm / Sat, Sep 23 / UCLA]** Creating Coding Fest / [RSVP](http://ccfest.rocks/register/)

## In the Lab 🔬
- Kero and Simeon worked on a Single Page App HTML game.
- Jim showed us some cool features of modern CSS like [non-rectangular layouts](https://www.sarasoueidan.com/blog/css-shapes/).
- Jacob and Rob are planning to implement a model from a deep learning paper.
- Danny is working through the [polls app tutorial](https://docs.djangoproject.com/en/1.11/intro/tutorial01/) to learn Django.

## Plans for Next Meeting (August 28, 2017) + Future 🔮
- Show-and-tell. Maybe?
- Potential tutorial topics: Timing, service workers, technical writing/documentation
- Urban Drool Tool: Setting up docs in a [wiki](https://github.com/codelaboc/CA-Stormwater-Data-Challenge/wiki/About-Urban-Drool-Tool) (including [how to set up locally](https://github.com/codelaboc/CA-Stormwater-Data-Challenge/blob/docker/docker_readme.md))
- 💡: Build a CodeLab Calendar

**Comment by jimthoburn** [comment]
Great write-up! Thanks for posting this, Rob.
